/**
 * dungeon-forge -- Procedural dungeon generator powered by jobs-algo.
 *
 * A playable game that uses the job scheduler to break dungeon generation
 * into small parallel work items spread across urgency buckets.
 * Each "floor" of the dungeon is a job -- rooms, encounters, loot, and
 * narrative are all generated by real Ollama inference.
 *
 * Difficulty modes:
 *   easy   -- small rooms, simple encounters, generous loot
 *   hard   -- complex rooms, deadly encounters, scarce loot
 *
 * Run:
 *   npx tsx examples/dungeon-forge/dungeon-forge.ts --difficulty easy --floors 5
 *   npx tsx examples/dungeon-forge/dungeon-forge.ts --difficulty hard --floors 8
 */

import { JobsAlgorithmImpl } from '../../src/integration/jobs-algorithm.js';
import { OllamaDirectExecutor } from '../../src/integration/ollama/ollama-executor.js';
import { computeSignature } from '../../src/algorithm/signature.js';
import type { AlgorithmEvent, Signature } from '../../src/types/index.js';
import { DEFAULT_CONFIG } from '../../src/types/index.js';
import fs from 'node:fs';
import path from 'node:path';

// ── Difficulty presets ──
// Shorter cacheExpiry = more urgent = generated first by the scheduler

interface DifficultyPreset {
  label: string;
  floors: number;
  roomsPerFloor: [number, number]; // min, max
  encounterRate: number;  // 0-1, chance a room has an encounter
  lootRate: number;       // 0-1, chance a room has loot
  roomUrgency: number;   // cacheExpiryMs for room generation (lower = more urgent)
  encounterUrgency: number;
  lootUrgency: number;
  narrativeUrgency: number;
  roomPrompt: string;
  encounterPrompt: string;
  lootPrompt: string;
  narrativePrompt: string;
}

const DIFFICULTIES: Record<string, DifficultyPreset> = {
  easy: {
    label: 'Easy',
    floors: 5,
    roomsPerFloor: [3, 5],
    encounterRate: 0.4,
    lootRate: 0.7,
    roomUrgency: 8_000,
    encounterUrgency: 15_000,
    lootUrgency: 20_000,
    narrativeUrgency: 30_000,
    roomPrompt: 'Describe a bright, welcoming dungeon room in 2-3 sentences. Include one interesting feature like a fountain, mural, or comfortable resting spot. This is an easy-difficulty dungeon.',
    encounterPrompt: 'Describe a minor dungeon encounter that a novice adventurer could handle. Include the creature type, its motivation, and one way to avoid fighting it. Keep it to 2-3 sentences. Easy difficulty.',
    lootPrompt: 'Describe a useful dungeon treasure find. Include the item name, what it does, and why it would help an adventurer. Keep it to 1-2 sentences. Easy difficulty, generous loot.',
    narrativePrompt: 'Write a brief (2-3 sentence) narrative hook for a dungeon floor that gives the player hope and hints at a reward ahead. This is an easy dungeon, so keep it lighthearted.',
  },
  hard: {
    label: 'Hard',
    floors: 8,
    roomsPerFloor: [4, 7],
    encounterRate: 0.8,
    lootRate: 0.3,
    roomUrgency: 5_000,
    encounterUrgency: 10_000,
    lootUrgency: 12_000,
    narrativeUrgency: 20_000,
    roomPrompt: 'Describe a dark, dangerous dungeon room in 2-3 sentences. Include one environmental hazard like a trap, pit, or toxic gas. This is a hard-difficulty dungeon with lethal challenges.',
    encounterPrompt: 'Describe a dangerous dungeon encounter that could easily kill an unprepared adventurer. Include the creature type, its deadly ability, and a hint about a weakness. Keep it to 2-3 sentences. Hard difficulty, lethal encounters.',
    lootPrompt: 'Describe a dungeon treasure that is hard to reach or comes with a catch. Include what it is and why it might not be worth the risk. Keep it to 1-2 sentences. Hard difficulty, scarce and dangerous loot.',
    narrativePrompt: 'Write a brief (2-3 sentence) narrative hook for a dungeon floor that creates dread and a sense of escalating danger. This is a hard dungeon, so make it foreboding.',
  },
};

// ── Game data structures ──

interface DungeonRoom {
  id: string;
  floor: number;
  roomNumber: number;
  description: string;
  encounter: string | null;
  loot: string | null;
}

interface DungeonFloor {
  floorNumber: number;
  narrative: string;
  rooms: DungeonRoom[];
}

interface DungeonRun {
  difficulty: string;
  timestamp: string;
  floors: DungeonFloor[];
  wallMs: number;
  totalRooms: number;
  encounters: number;
  loot: number;
  profileSnapshots: Array<{
    signature: string;
    name: string;
    sampleCount: number;
    warm: boolean;
    wallEWMA: number;
  }>;
}

// ── Dungeon Forge ──

function parseArgs(argv: string[]): Record<string, string> {
  const parsed: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].slice(2);
      const value = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : 'true';
      parsed[key] = value;
      if (value !== 'true') i++;
    }
  }
  return parsed;
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

async function generateDungeon(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const difficultyName = String(args.difficulty || 'easy').toLowerCase();
  const difficulty = DIFFICULTIES[difficultyName];
  if (!difficulty) {
    console.error('Unknown difficulty: ' + difficultyName + '. Use "easy" or "hard".');
    process.exit(1);
  }
  const floorCount = Number(args.floors || difficulty.floors);
  const slots = Number(args.slots || 4);
  const model = String(args.model || 'qwen2.5:0.5b');
  const outputDir = String(args.output || '.cache/dungeon-forge');

  console.log('');
  console.log('='.repeat(60));
  console.log('  DUNGEON FORGE -- ' + difficulty.label.toUpperCase() + ' MODE');
  console.log('  Floors: ' + floorCount + '  |  Slots: ' + slots + '  |  Model: ' + model);
  console.log('  Encounter rate: ' + (difficulty.encounterRate * 100) + '%  |  Loot rate: ' + (difficulty.lootRate * 100) + '%');
  console.log('='.repeat(60));
  console.log('');
  console.log('  Generating dungeon with jobs-algo...');
  console.log('  Room urgency: ' + difficulty.roomUrgency + 'ms');
  console.log('  Encounter urgency: ' + difficulty.encounterUrgency + 'ms');
  console.log('  Loot urgency: ' + difficulty.lootUrgency + 'ms');
  console.log('  Narrative urgency: ' + difficulty.narrativeUrgency + 'ms');
  console.log('');

  const config: Partial<typeof DEFAULT_CONFIG> = {
    ...DEFAULT_CONFIG,
    maxParallelism: slots,
    defaultCacheExpiryMs: 30_000,
    defaultRefreshRateMs: 300_000,
    coldStartSamples: 2,
    cacheDir: path.join(outputDir, 'cache'),
  };

  const algo = new JobsAlgorithmImpl(config);
  algo.setMissionControl(new OllamaDirectExecutor({
    model,
    timeoutMs: 60_000,
    maxTokens: 150,
  }));

  // Collect results per floor
  const floors: DungeonFloor[] = [];
  const roomResults = new Map<string, { description: string }>();
  const encounterResults = new Map<string, { description: string }>();
  const lootResults = new Map<string, { description: string }>();
  const narrativeResults = new Map<string, { description: string }>();

  // Signatures
  const roomSig = computeSignature({ type: 'gen-room', entity: 'dungeon', argSchema: { difficulty: 'string', floor: 'string', room: 'string' } });
  const encounterSig = computeSignature({ type: 'gen-encounter', entity: 'dungeon', argSchema: { difficulty: 'string', floor: 'string', room: 'string' } });
  const lootSig = computeSignature({ type: 'gen-loot', entity: 'dungeon', argSchema: { difficulty: 'string', floor: 'string', room: 'string' } });
  const narrativeSig = computeSignature({ type: 'gen-narrative', entity: 'dungeon', argSchema: { difficulty: 'string', floor: 'string' } });

  // Subscribe to all signatures
  let totalCompleted = 0;
  let totalFailed = 0;
  let totalJobs = 0;

  for (const sig of [roomSig, encounterSig, lootSig, narrativeSig]) {
    algo.subscribe(sig, (event: AlgorithmEvent) => {
      if (event.type === 'job_complete') {
        totalCompleted++;
        try {
          const parsed = JSON.parse(event.result.toString('utf8'));
          if (sig === roomSig) roomResults.set(event.jobId, { description: parsed.content || parsed.summary || '' });
          else if (sig === encounterSig) encounterResults.set(event.jobId, { description: parsed.content || parsed.summary || '' });
          else if (sig === lootSig) lootResults.set(event.jobId, { description: parsed.content || parsed.summary || '' });
          else if (sig === narrativeSig) narrativeResults.set(event.jobId, { description: parsed.content || parsed.summary || '' });
        } catch { /* non-JSON result */ }

        if (totalCompleted % 5 === 0 || totalCompleted + totalFailed === totalJobs) {
          const pct = ((totalCompleted + totalFailed) / totalJobs * 100).toFixed(0);
          process.stdout.write('  [' + pct + '%] ' + totalCompleted + '/' + totalJobs + ' rooms generated\n');
        }
      } else if (event.type === 'job_failed') {
        totalFailed++;
        process.stdout.write('  FAILED: ' + (event.error || 'unknown').slice(0, 60) + '\n');
      }
    });
  }

  // Generate dungeon structure and enqueue jobs
  const startTime = Date.now();
  const roomIdMap = new Map<string, { floor: number; roomNumber: number }>();
  const narrativeJobIds = new Map<number, string>();

  for (let f = 0; f < floorCount; f++) {
    const roomCount = randomInt(difficulty.roomsPerFloor[0], difficulty.roomsPerFloor[1]);

    // Enqueue narrative for this floor (medium urgency)
    const narrativePayload = Buffer.from(JSON.stringify({
      type: 'gen-narrative',
      difficulty: difficultyName,
      floor: String(f + 1),
      prompt: difficulty.narrativePrompt + ' Floor ' + (f + 1) + ' of ' + floorCount + '.',
    }), 'utf8');
    const nJobId = algo.enqueue(narrativeSig, narrativePayload, {
      cacheExpiryMs: difficulty.narrativeUrgency,
      refreshRateMs: 300_000,
    });
    narrativeJobIds.set(f, nJobId);
    totalJobs++;

    // Enqueue rooms for this floor (most urgent -- generated first)
    for (let r = 0; r < roomCount; r++) {
      const roomPayload = Buffer.from(JSON.stringify({
        type: 'gen-room',
        difficulty: difficultyName,
        floor: String(f + 1),
        room: String(r + 1),
        prompt: difficulty.roomPrompt + ' Floor ' + (f + 1) + ', Room ' + (r + 1) + ' of ' + roomCount + '.',
      }), 'utf8');
      const rJobId = algo.enqueue(roomSig, roomPayload, {
        cacheExpiryMs: difficulty.roomUrgency,
        refreshRateMs: 300_000,
      });
      roomIdMap.set(rJobId, { floor: f, roomNumber: r });
      totalJobs++;

      // Maybe enqueue an encounter (medium urgency)
      if (Math.random() < difficulty.encounterRate) {
        const ePayload = Buffer.from(JSON.stringify({
          type: 'gen-encounter',
          difficulty: difficultyName,
          floor: String(f + 1),
          room: String(r + 1),
          prompt: difficulty.encounterPrompt + ' Floor ' + (f + 1) + ', Room ' + (r + 1) + '.',
        }), 'utf8');
        algo.enqueue(encounterSig, ePayload, {
          cacheExpiryMs: difficulty.encounterUrgency,
          refreshRateMs: 300_000,
        });
        totalJobs++;
      }

      // Maybe enqueue loot (low urgency)
      if (Math.random() < difficulty.lootRate) {
        const lPayload = Buffer.from(JSON.stringify({
          type: 'gen-loot',
          difficulty: difficultyName,
          floor: String(f + 1),
          room: String(r + 1),
          prompt: difficulty.lootPrompt + ' Floor ' + (f + 1) + ', Room ' + (r + 1) + '.',
        }), 'utf8');
        algo.enqueue(lootSig, lPayload, {
          cacheExpiryMs: difficulty.lootUrgency,
          refreshRateMs: 300_000,
        });
        totalJobs++;
      }
    }
  }

  console.log('  Total jobs enqueued: ' + totalJobs + ' (rooms + encounters + loot + narratives)');
  console.log('');

  // Wait for completion
  const timeout = Number(args.timeout || 300_000);
  const deadline = Date.now() + timeout;
  while (totalCompleted + totalFailed < totalJobs && Date.now() < deadline) {
    await new Promise(r => setTimeout(r, 500));
  }

  const totalWallMs = Date.now() - startTime;

  // Assemble dungeon from results
  const dungeonFloors: DungeonFloor[] = [];
  for (let f = 0; f < floorCount; f++) {
    const floor: DungeonFloor = {
      floorNumber: f + 1,
      narrative: 'A dark corridor stretches before you...',
      rooms: [],
    };

    // Find narrative
    for (const [jobId, result] of narrativeResults) {
      if (result.description) {
        floor.narrative = result.description.replace(/\n/g, ' ').trim();
        break;
      }
    }

    dungeonFloors.push(floor);
  }

  // Assign rooms to floors
  for (const [jobId, info] of roomIdMap) {
    const roomResult = roomResults.get(jobId);
    const encounterJobId = [...encounterResults.keys()].find(() => false); // encounters are separate jobs
    const floor = dungeonFloors[info.floor];

    const room: DungeonRoom = {
      id: 'F' + (info.floor + 1) + 'R' + (info.roomNumber + 1),
      floor: info.floor + 1,
      roomNumber: info.roomNumber + 1,
      description: roomResult?.description?.replace(/\n/g, ' ').trim() || 'A stone chamber with damp walls.',
      encounter: null,
      loot: null,
    };
    floor.rooms.push(room);
  }

  // Assign encounters and loot to rooms
  for (const [jobId, result] of encounterResults) {
    for (const floor of dungeonFloors) {
      for (const room of floor.rooms) {
        if (!room.encounter) {
          room.encounter = result.description?.replace(/\n/g, ' ').trim() || null;
          break;
        }
      }
      if (dungeonFloors.some(f => f.rooms.some(r => r.encounter === null) === false)) break;
    }
  }

  for (const [jobId, result] of lootResults) {
    for (const floor of dungeonFloors) {
      for (const room of floor.rooms) {
        if (!room.loot) {
          room.loot = result.description?.replace(/\n/g, ' ').trim() || null;
          break;
        }
      }
      if (dungeonFloors.some(f => f.rooms.some(r => r.loot === null) === false)) break;
    }
  }

  // Profile snapshots
  const profileSnaps = [];
  for (const [name, sig] of [['room', roomSig], ['encounter', encounterSig], ['loot', lootSig], ['narrative', narrativeSig]] as [string, Signature][]) {
    const profile = algo.getProfile(sig);
    if (profile) {
      profileSnaps.push({
        signature: sig.slice(0, 10),
        name: name as string,
        sampleCount: profile.sampleCount,
        warm: profile.sampleCount >= 2,
        wallEWMA: Math.round(profile.wallTimeMsEWMA),
      });
    }
  }

  // Print the dungeon
  console.log('');
  console.log('='.repeat(60));
  console.log('  DUNGEON FORGE -- ' + difficulty.label.toUpperCase() + ' DUNGEON');
  console.log('='.repeat(60));
  console.log('');

  const totalRooms = dungeonFloors.reduce((s, f) => s + f.rooms.length, 0);
  const totalEncounters = dungeonFloors.reduce((s, f) => s + f.rooms.filter(r => r.encounter).length, 0);
  const totalLoot = dungeonFloors.reduce((s, f) => s + f.rooms.filter(r => r.loot).length, 0);

  console.log('  Floors: ' + floorCount + '  |  Rooms: ' + totalRooms + '  |  Encounters: ' + totalEncounters + '  |  Loot: ' + totalLoot);
  console.log('  Completed: ' + totalCompleted + '/' + totalJobs + '  |  Failed: ' + totalFailed);
  console.log('  Wall time: ' + (totalWallMs / 1000).toFixed(1) + 's  |  Throughput: ' + (totalCompleted / (totalWallMs / 1000)).toFixed(1) + ' j/s');
  console.log('');

  for (const floor of dungeonFloors) {
    console.log('  ── Floor ' + floor.floorNumber + ' ──');
    console.log('  ' + floor.narrative);
    console.log('');
    for (const room of floor.rooms) {
      console.log('    ' + room.id + ': ' + room.description);
      if (room.encounter) {
        console.log('      ENCOUNTER: ' + room.encounter);
      }
      if (room.loot) {
        console.log('      LOOT: ' + room.loot);
      }
      console.log('');
    }
  }

  // Profile learning
  console.log('  PROFILE LEARNING:');
  for (const ps of profileSnaps) {
    console.log('    ' + ps.name.padEnd(12) + ' samples=' + String(ps.sampleCount).padEnd(3) + ' warm=' + String(ps.warm).padEnd(5) + ' wall=' + ps.wallEWMA + 'ms');
  }
  console.log('');

  // Save report
  const dungeon: DungeonRun = {
    difficulty: difficultyName,
    timestamp: new Date().toISOString(),
    floors: dungeonFloors,
    wallMs: totalWallMs,
    totalRooms,
    encounters: totalEncounters,
    loot: totalLoot,
    profileSnapshots: profileSnaps,
  };

  fs.mkdirSync(outputDir, { recursive: true });
  const reportPath = path.join(outputDir, 'dungeon-' + difficultyName + '-' + Date.now() + '.json');
  fs.writeFileSync(reportPath, JSON.stringify(dungeon, null, 2), 'utf8');
  console.log('  Report saved: ' + reportPath);

  algo['scheduler'].clearAllRefreshTimers();
  await algo.shutdown();
}

const isMain = process.argv[1]?.includes('dungeon-forge');
if (isMain) {
  generateDungeon().catch((err) => {
    console.error('Dungeon Forge failed:', err);
    process.exit(1);
  });
}

export { DIFFICULTIES, DungeonRoom, DungeonFloor, DungeonRun };
